/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#f8f9fa',
        foreground: '#231942',
        card: '#ffffff',
        card_foreground: '#231942',
        popover: '#ffffff',
        popover_foreground: '#231942',
        primary: '#5E548E',
        primary_foreground: '#ffffff',
        secondary: '#9F86C0',
        secondary_foreground: '#ffffff',
        muted: '#e9ecef',
        muted_foreground: '#6c757d',
        accent: '#BE95C4',
        accent_foreground: '#ffffff',
        destructive: '#E56B6F',
        destructive_foreground: '#ffffff',
        border: 'rgba(0, 0, 0, 0.1)',
        input: 'transparent',
        input_background: '#ffffff',
        switch_background: '#cbced4',
        font_weight_medium: 500,
        font_weight_normal: 400,
        ring: '#5E548E',
        chart_1: '#231942',
        chart_2: '#5E548E',
        chart_3: '#9F86C0',
        chart_4: '#BE95C4',
        chart_5: '#E0B1CB',
        sidebar: '#231942',
        sidebar_foreground: '#ffffff',
        sidebar_primary: '#5E548E',
        sidebar_primary_foreground: '#ffffff',
        sidebar_accent: '#9F86C0',
        sidebar_accent_foreground: '#ffffff',
        sidebar_border: 'rgba(255, 255, 255, 0.1)',
        sidebar_ring: '#ffffff',
      },
    },
  },
  plugins: [],
}
